### PR TITLE
Multitargeting Support

### PR DESCRIPTION
**Pull request by robertmclaws**
- Added .NET 8.0 and .NET 6.0 LTS releases
- Removed .NET 7.0 as it is no longer supported by Microsoft

### CODE REVIEW

**Comment by KristofferStrube** [comment]
Hey @robertmclaws, thanks for the interest. 😊

The wrapper is not done, so I tend to wait until I have covered all the planned API parts before changing the version and only releasing incremented alpha versions until this is done. This enables me to make breaking changes while I'm still implementing all the base parts of the wrapper in case I find out that other parts of the API make it necessary to change the existing parts.

`Blazor.WebIDL`, a dependency of `Blazor.DOM`, uses features only available in .NET 7 and forward, so the library cannot multi-target for .NET 6. So, to keep this from breaking people who might already have used this in .NET 7 projects, this will have to keep targeting .NET 7.

Next, on whether to target .NET 8. Targeting newer versions of .NET can improve performance, but for this scenario this is not the case. Any improvements to performance would be implemented in the dotnet/blazor runtime, which is not limited by which version of .NET this library targets. So, I don't think it would add enough value to warrant targeting .NET 8 as well.

Even though Microsoft no longer supports .NET 7, it is still okay to target this version as the lowest common denominator. There are still people using Blazor in .NET 5, and if I could have made support for this as well, I would have.

Lastly, on using version ranges for the `Microsoft.AspNetCore.Components.Web`. I would rather use a specific package version for references to ensure the package works for that specific version. This does not stop others from targeting newer versions. Additionally, targeting a range can cause dependency changes when releasing a new version of the package without specifically having specified that a new version should be used. Normally, this is not a problem, but it could cause unexpected behavioral changes unrelated to other changes made in a new library version, which I would like to avoid where possible.

A lot of this is obviously my personal preferences, which I should have made clear through a CONTRIBUTOR.md file. I will try to incorporate the above points in my existing template for a CONTRIBUTOR.md file and add it to the repository very soon.

**Comment by robertmclaws** [comment]
So, thanks for the detailed info. The problem with pinning a specific version of Components.Web is that pulling in this NuGet package also tries to install the .NET 7 version in my .NET 8 app, when I then have to override manually.

Even if you use the technique to keep .NET 7 & .NET 8 support, you _still_ need to be targeting the right version of your dependencies to the right versions of the Framework, otherwise you will have unexpected side-effects.

**Comment by KristofferStrube** [comment]
As it is a part of all Blazor templates to install the appropriate version of `Microsoft.AspNetCore.Components.Web` for your version of .NET, I expect that all have already referenced a specific version of the package before adding my library to their project. My project should not enforce that people use the correct version of `Microsoft.AspNetCore.Components.Web`.

**Comment by robertmclaws** [comment]
It does when you're using it in a library and not part of an app, and up to that point you have not needed to reference that NuGet package before. 

I see what you are saying, however NuGet packages *should* (and most do) enforce that you use the right package for the version of the framework you are using. That's why the technique exists.

I just want to point out that I submitted the PR because this library messed up my library when I tried to install it.

**Pull request closed without merging**
